{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/release-tools/issues/69/comments/27856747.json"}, "html": {"href": "#!/osrf/release-tools/issues/69#comment-27856747"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/release-tools/issues/69.json"}}, "type": "issue", "id": 69, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "title": "Problem apt-getting linux packages"}, "content": {"raw": "Xenial metadata was wrong and generated trusty files, which were uploaded to the repo instead of the real trusty files. I've fixed the problem in: \nhttps://bitbucket.org/ignitionrobotics/ign-transport-release/commits/73a566342e0310db6568de8e9e24317c000eaddc\n\nAnd new packages 1.2.0-2 for xenial and trusty are in the queue now.", "markup": "markdown", "html": "<p>Xenial metadata was wrong and generated trusty files, which were uploaded to the repo instead of the real trusty files. I've fixed the problem in: \n<a href=\"https://bitbucket.org/ignitionrobotics/ign-transport-release/commits/73a566342e0310db6568de8e9e24317c000eaddc\" rel=\"nofollow\" class=\"ap-connect-link\">https://bitbucket.org/ignitionrobotics/ign-transport-release/commits/73a566342e0310db6568de8e9e24317c000eaddc</a></p>\n<p>And new packages 1.2.0-2 for xenial and trusty are in the queue now.</p>", "type": "rendered"}, "created_on": "2016-05-17T17:47:00.162906+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": null, "type": "issue_comment", "id": 27856747}], "page": 1, "size": 1}